# You can define a fallback output for all modules that don't define their own.
#output = "Tests/Swift/Generated/GeneratedMocks.swift"

[modules.MVVMPrototype]
output = "MVVMPrototypeTests/Generated/GeneratedMocks+MVVMPrototype.swift"
# Standard imports added to the generated file(s).
imports = ["Foundation"]
# @testable imports if needed.
testableImports = ["MVVMPrototype"]
sources = [
    "MVVMPrototype/Network/*.swift",
]
exclude = []#["ExcludedTestClass"]
# Optionally you can use a regular expression to filter only specific classes/protocols.
# regex = ""

[modules.MVVMPrototype.options]
glob = true
# Docstrings are preserved by default, comments are omitted.
keepDocumentation = false
# enableInheritance = false
# protocolsOnly = true
# omitHeaders = true

# If specified, Cuckoo can also get sources for the module from an Xcode target.
#[modules.MVVMPrototype.xcodeproj]
# Path to folder with .xcodeproj, omit this if it's at the same level as Cuckoofile.
#path = "."
#target = "MVVMPrototype"
